fixed thresholds at the Field level:measureValueCompletenessThreshold and at the Table level: measurePersonCompletenessThreshold
OHDSI/DataQualityDashboard pull request #464
Opened 2023-06-21 11:18 UTC by dimshitc

in the Field level:measureValueCompletenessThreshold, the following logic was used:
set measurevaluecompletenessthreshold = 0 where isrequired = 'Yes' 
;
set measurevaluecompletenessthreshold = 100 where isrequired = 'No' 
;
The Table level: measurePersonCompletenessThreshold was set the same as for v5.3, with additionaly set to 95 for the EPISODE table

2023-06-24 00:59 UTC, katy-sadowski requested changes
Thanks so much for fixing this!

In checking against the older files I noticed that `measureValueCompleteness` for the DEATH table does not match `isRequired` in the v5.2 and v5.3 threshold files (i.e. should be 0 where the field is required, as you've done in the 5.4 file). Could you please also add that change to the other 2 threshold files?

2023-06-26 10:18 UTC, dimshitc commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +DEATH,CDM,No,,No,95,,No,,,,"The death domain contains the clinical event for how and when a Person dies. A person can have up to one record if the source system contains evidence about the Death, suc
My bad, I didn't take measurePersonCompleteness value into account. Not sure why I put 95 there. I should have put 100 there, and measurePersonCompleteness ='Yes', so the status will be always ='Pass', but user can assess the Death table using DQD.
But what is the behaviour of this check, if the Death table is not populated?

2023-06-26 10:18 UTC, dimshitc commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +EPISODE,CDM,No,,No,95,,No,,,,"The EPISODE table aggregates lower-level clinical events (VISIT_OCCURRENCE, DRUG_EXPOSURE, PROCEDURE_OCCURRENCE, DEVICE_EXPOSURE) into a higher-level abstraction represe
Same idea as with Death:
The only difference is that Episode table is used rarely yet.

2023-06-28 14:00 UTC, katy-sadowski commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +DEATH,CDM,No,,No,95,,No,,,,"The death domain contains the clinical event for how and when a Person dies. A person can have up to one record if the source system contains evidence about the Death, suc
I believe if it's `Yes` + `100`, and the death table is empty, the check will pass (for non-zero thresholds you need to exceed the threshold in order to fail).  If the death table is not present in the CDM then the check will be marked as NOT_APPLICABLE.  I'm fine with either Yes+100 or No+null here.

2023-06-28 14:01 UTC, katy-sadowski commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +EPISODE,CDM,No,,No,95,,No,,,,"The EPISODE table aggregates lower-level clinical events (VISIT_OCCURRENCE, DRUG_EXPOSURE, PROCEDURE_OCCURRENCE, DEVICE_EXPOSURE) into a higher-level abstraction represe
In this case since it's rarely used maybe it makes the most sense to keep this one as `No` and remove the threshold.

2023-06-28 14:03 UTC, katy-sadowski commented on inst/csv/OMOP_CDMv5.4_Concept_Level.csv
> +MEASUREMENT,MEASUREMENT_CONCEPT_ID,36306178,"Glomerular filtration rate/1.73 sq M.predicted among blacks [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)",,,,,,,,,,,
per my comment on https://github.com/OHDSI/DataQualityDashboard/issues/420, maybe we should actually allow both unit concept IDs here, to accommodate both vocab versions?

2023-06-28 14:04 UTC, katy-sadowski commented on inst/csv/OMOP_CDMv5.4_Concept_Level.csv
> +MEASUREMENT,MEASUREMENT_CONCEPT_ID,36303797,"Glomerular filtration rate/1.73 sq M.predicted among non-blacks [Volume Rate/Area] in Serum, Plasma or Blood by Creatinine-based formula (CKD-EPI)",,,,,,,
same here

2023-07-10 12:20 UTC, dimshitc commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +DEATH,CDM,No,,No,95,,No,,,,"The death domain contains the clinical event for how and when a Person dies. A person can have up to one record if the source system contains evidence about the Death, suc
Yes+100 to be it

2023-07-10 12:22 UTC, dimshitc commented on inst/csv/OMOP_CDMv5.4_Table_Level.csv
> +EPISODE,CDM,No,,No,95,,No,,,,"The EPISODE table aggregates lower-level clinical events (VISIT_OCCURRENCE, DRUG_EXPOSURE, PROCEDURE_OCCURRENCE, DEVICE_EXPOSURE) into a higher-level abstraction represe
No + NULL to be it

2023-07-11 17:58 UTC, katy-sadowski approved these changes
@dimshitc I ended up fixing the failing tests in a separate PR: https://github.com/OHDSI/DataQualityDashboard/pull/468 (I tried pushing to your fork but got a permission denied so just pushed my changes in a PR on the main repo).  As such, I think we can go ahead and merge this PR despite the failing tests, and then right afterwards, merge my PR #468 .

2023-07-18 14:30 UTC, merged